=== Naturalkidv1/LenguajedeMarcasJJ1DAW/LdM Dias 31-40/LdM Dia 34/relacion_final_xml (completa)/Ejer_20_y_21/motorsol.dtd
<!ELEMENT motorsol (piezas, motores, empleados, secciones)>

<!ELEMENT piezas (pieza+)>
<!ELEMENT pieza EMPTY>
<!ATTLIST pieza
	codpieza ID #REQUIRED
	compuestode IDREFS #IMPLIED
>

<!ELEMENT motores (motor+)>
<!ELEMENT motor (trabajador+)>
<!ATTLIST motor
	codmotor ID #REQUIRED
	responsable IDREF #REQUIRED
	piezasUsadas IDREFS #REQUIRED
>
<!ELEMENT trabajador EMPTY>
<!ATTLIST trabajador
	codempleadoT IDREF #REQUIRED
	trabajadoresACargo IDREFS #IMPLIED
>

<!ELEMENT empleados (empleado+)>
<!ELEMENT empleado EMPTY>
<!ATTLIST empleado
	codempleado ID #REQUIRED
>

<!ELEMENT secciones (seccion+)>
<!ELEMENT seccion EMPTY>
<!ATTLIST seccion
	codsec ID #REQUIRED
	trabajaEn IDREFS #IMPLIED
>

=== Naturalkidv1/LenguajedeMarcasJJ1DAW/LdM Dias 31-40/LdM Dia 34/relacion_final_xml/Ejer_20_y_21/MOTORSOL.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE motorsol SYSTEM "motorsol.dtd">

<motorsol>

	<piezas>
		<pieza codpieza="p1" compuestode="p2"/>
		<pieza codpieza="p2"/>
		<pieza codpieza="p3" compuestode="p1"/>
		<pieza codpieza="p4"/>
	</piezas>

	<motores>
		<motor codmotor="m1" responsable="e1" piezasUsadas="p1 p4">
			<trabajador codempleadoT="e1" trabajadoresACargo="e2 e3"/>
			<trabajador codempleadoT="e4"/>
		</motor>
		<motor codmotor="m2" responsable="e4" piezasUsadas="p1 p4">
			<trabajador codempleadoT="e4"/>
		</motor>
	</motores>
	
	<empleados>
		<empleado codempleado="e1"/>
		<empleado codempleado="e2"/>
		<empleado codempleado="e3"/>
		<empleado codempleado="e4"/>
	</empleados>

	<secciones>
		<seccion codsec="s1" trabajaEn="m1 m2"/>
	</secciones>

</motorsol>
