=== Naturalkidv1/LenguajedeMarcasJJ1DAW/LdM Dias 31-40/LdM Dia 34/relacion_final_xml (completa)/Ejer_14_y_15/Ejercicio_14.dtd
<!ELEMENT banco ((clientes, sucursales)|(sucursales, clientes))>

<!ENTITY % idr "ID #REQUIRED">

<!ELEMENT clientes (cliente+)>
<!ELEMENT sucursales (sucursal+)>

<!ELEMENT cliente (prestamo*, cuenta+, prestamo*)+>
<!ATTLIST cliente nif %idr;>
<!ELEMENT prestamo EMPTY>
<!ATTLIST prestamo num %idr;>
<!ELEMENT cuenta EMPTY>
<!ATTLIST cuenta 
	cod IDREF #REQUIRED
	permiso (titular|autorizado) #REQUIRED
>

<!ELEMENT sucursal (cuenta_corriente+)>
<!ATTLIST sucursal id %idr;>
<!ELEMENT cuenta_corriente (domiciliacion*)>
<!ATTLIST cuenta_corriente cod %idr;>
<!ELEMENT domiciliacion EMPTY>
<!ATTLIST domiciliacion num %idr;>

=== Naturalkidv1/LenguajedeMarcasJJ1DAW/LdM Dias 31-40/LdM Dia 34/relacion_final_xml/Ejer_14/Ejercicio_14.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE banco SYSTEM "Ejercicio_14.dtd">

<banco>
	<clientes>
		<cliente nif="_11223344N">
			<prestamo num="_2551"/>
			<cuenta cod="_11" permiso="titular"/>
			<cuenta cod="_21" permiso="autorizado"/>
		</cliente>
		<cliente nif="_11223355Z">
			<cuenta cod="_11" permiso="autorizado"/>
		</cliente>
		<cliente nif="_11223366X">
			<cuenta cod="_21" permiso="titular"/>
			<prestamo num="_2552"/>
		</cliente>
	</clientes>

	<sucursales>
		<sucursal id="_1">
			<cuenta_corriente cod="_11">
				<domiciliacion num="_131"/>
			</cuenta_corriente>
		</sucursal>
		<sucursal id="_2">
			<cuenta_corriente cod="_21">
				<domiciliacion num="_231"/>
			</cuenta_corriente>
		</sucursal>
	</sucursales>
</banco>
