=== Naturalkidv1/LenguajedeMarcasJJ1DAW/LdM Dias 21-30/LdM Dia 30 (XML)/persona.dtd
<!ELEMENT persona (nombre, apellidos)> -- y -- 
<!ELEMENT persona (nombre, apellidos?)> -- apellidos opcional --
<!ELEMENT persona (nombre|apellidos)> -- o -- 
<!ELEMENT persona ((nombre, apellidos) | (apellidos, nombre))> -- permite que ambos ordenes existan --

<!ELEMENT persona (nombre, apellidos, direccion, (hombre|mujer)?, hijos?)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>

<!ELEMENT direccion (#PCDATA|provincia|poblacion)*>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>

<!ELEMENT hombre EMPTY>
<!ELEMENT mujer EMPTY>

<!ELEMENT hijos (hijo+)> -- 1 al menos --
<!ELEMENT hijos (hijo*)> -- desde 0 hasta infinito --
<!ELEMENT hijo (#PCDATA)>

=== Naturalkidv1/LenguajedeMarcasJJ1DAW/LdM Dias 21-30/LdM Dia 30/persona.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE peronsa SYSTEM "persona.dtd"> -- externo --

<!DOCTYPE persona 
[<!ELEMENT persona ((nombre, apellidos) | (apellidos, nombre))>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
]> -- interno --

<persona>
	<nombre>Miguel</nombre>
	<apellidos>Martínez Pérez</apellidos>
	<dirrecion>
		<provincia>Málaga</provincia>
		Calle Sant Cristo
		<poblacion>Istán</poblacion>
	</dirrecion>
	<hombre/>
	<hijos>
		<hijo>Juan</hijo>
		<hijo>Pedro</hijo>
	</hijos>
</persona>
