<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE libro [
<!ELEMENT libro ( titulo | disponible | autor | formato | publicacion | precio | descuento | enlacelibro )*>
<!ELEMENT autor ( #PCDATA )>
<!ELEMENT descuento EMPTY>
<!ATTLIST descuento cantidad CDATA #REQUIRED>
<!ELEMENT disponible EMPTY>
<!ATTLIST disponible tiempo CDATA #REQUIRED>
<!ELEMENT enlacelibro EMPTY>
<!ATTLIST enlacelibro href CDATA #REQUIRED>
<!ELEMENT formato (#PCDATA)>
<!ELEMENT precio EMPTY>
<!ATTLIST precio cantidad CDATA #REQUIRED>
<!ATTLIST precio moneda CDATA #REQUIRED>
<!ELEMENT publicacion ( #PCDATA )>
<!ELEMENT titulo ( #PCDATA )>
]>

<libro>
	<titulo> Cien años de soledad </titulo>
	<disponible tiempo="24"></disponible>
	<autor> Gabriel García Márquez </autor>
	<formato> Rústica </formato>
	<publicacion>1967 </publicacion>
	<precio cantidad="39.99" moneda="$"></precio>
	<descuento cantidad="5"></descuento>
	<enlacelibro href="/exec/ISBN/84-473-0619-4"></enlacelibro>
</libro>