=== Naturalkidv1/LenguajedeMarcasJJ1DAW/LdM Dias 41-50/LdM Dia 43/Repaso/Repaso.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="horario" type="tipoHorario"/>

<xs:complexType name="tipoHorario">
    <xs:sequence>
        <xs:element name="dia" type="tipoDia" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="tipoDia">
    <xs:sequence>
        <xs:element name="numdia" type="tipoNumDia"/>
        <xs:element name="tarea" type="tipoTarea" maxOccurs="unbounded"/> 
    </xs:sequence>
    <xs:attribute name="coddia" type="xs:ID" use="required"/>
</xs:complexType>

<xs:simpleType name="tipoNumDia">
    <xs:restriction base="xs:positiveInteger">
        <xs:minInclusive value="1"/>
        <xs:maxExclusive value="6"/>
    </xs:restriction>

</xs:simpleType>

<xs:complexType name="tipoTarea">
    <xs:sequence>
        <xs:element name="hora-ini" type="xs:positiveInteger"/>
        <xs:element name="hora-fin" type="xs:positiveInteger"/>
        <xs:element name="nombre" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="prioridad" type="xs:string" use="optional"/>
</xs:complexType>

</xs:schema>

=== Naturalkidv1/LenguajedeMarcasJJ1DAW/LdM Dias 41-50/LdM Dia 43/Repaso/horario_repaso.xml
<?xml version="1.0" encoding="UTF-8"?>

<horario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Repaso.xsd">
    <dia coddia="_1">
        <numdia>1</numdia>
        <tarea prioridad="media">
            <hora-ini>12</hora-ini>
            <hora-fin>14</hora-fin>
            <nombre>Tutorías</nombre>
        </tarea>
    </dia>
    <dia coddia="_2">
        <numdia>2</numdia>
        <tarea prioridad="alta">
            <hora-ini>12</hora-ini>
            <hora-fin>14</hora-fin>
            <nombre>Autómatas</nombre>
        </tarea>
    </dia>
    <dia coddia="_3">
        <numdia>4</numdia>
        <tarea prioridad="alta">
            <hora-ini>9</hora-ini>
            <hora-fin>11</hora-fin>
            <nombre>Procesadores de lenguajes</nombre>
        </tarea>
        <tarea>
            <hora-ini>16</hora-ini>
            <hora-fin>17</hora-fin>
            <nombre>EDI</nombre>
        </tarea>
    </dia>
    <dia coddia="_4">
        <numdia>3</numdia>
        <tarea prioridad="alta">
            <hora-ini>9</hora-ini>
            <hora-fin>11</hora-fin>
            <nombre>Procesadores de lenguajes</nombre>
        </tarea>
    </dia>
    <dia coddia="_5">
        <numdia>5</numdia>
        <tarea prioridad="baja">
            <hora-ini>17</hora-ini>
            <hora-fin>18</hora-fin>
            <nombre>Ver la tele</nombre>
        </tarea>
    </dia>
</horario>
